/**
 * Migration: Add QR / Scan tracking tables
 * Run: node src/migrations/add_qr_tables.js
 */

const { pool } = require('../src/config/database');
require('dotenv').config();

const migrations = [

  // ── ITEM SKUS ─────────────────────────────────────────────────────────────
  // Stores every QR-labelled item (physical product or document)
  `CREATE TABLE IF NOT EXISTS item_skus (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id       UUID REFERENCES tenants(id) ON DELETE CASCADE,
    -- NULL tenant_id = generic QR generated by Super Admin / Client Servicing
    record_id       UUID REFERENCES records(id) ON DELETE CASCADE,
    -- NULL record_id = unassigned/generic QR not yet mapped to an item
    module_id       UUID REFERENCES modules(id) ON DELETE SET NULL,
    sku_code        VARCHAR(100) UNIQUE NOT NULL,
    label_type      VARCHAR(20) DEFAULT 'item',
    -- 'item' = physical product, 'document' = job card / invoice etc.
    generated_by    UUID REFERENCES users(id) ON DELETE SET NULL,
    is_assigned     BOOLEAN DEFAULT false,
    -- false = generic QR (super admin bulk print), true = tied to a record
    qr_data         TEXT,
    -- base64 PNG of the QR code (stored so label can be reprinted anytime)
    created_at      TIMESTAMPTZ DEFAULT NOW()
  )`,

  // ── SCAN EVENTS ──────────────────────────────────────────────────────────
  // Every phone scan logs here — like a courier tracking trail
  `CREATE TABLE IF NOT EXISTS scan_events (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id   UUID REFERENCES tenants(id) ON DELETE CASCADE,
    sku_id      UUID NOT NULL REFERENCES item_skus(id) ON DELETE CASCADE,
    scanned_by  UUID REFERENCES users(id) ON DELETE SET NULL,
    action      VARCHAR(50) DEFAULT 'scanned',
    -- 'scanned' | 'received' | 'dispatched' | 'checked' | 'moved' | 'assigned'
    location    VARCHAR(255),
    notes       TEXT,
    scanned_at  TIMESTAMPTZ DEFAULT NOW()
  )`,

  // Indexes
  `CREATE INDEX IF NOT EXISTS idx_item_skus_tenant   ON item_skus(tenant_id)`,
  `CREATE INDEX IF NOT EXISTS idx_item_skus_record   ON item_skus(record_id)`,
  `CREATE INDEX IF NOT EXISTS idx_item_skus_code     ON item_skus(sku_code)`,
  `CREATE INDEX IF NOT EXISTS idx_scan_events_sku    ON scan_events(sku_id)`,
  `CREATE INDEX IF NOT EXISTS idx_scan_events_tenant ON scan_events(tenant_id)`,
];

async function run() {
  const client = await pool.connect();
  try {
    await client.query('BEGIN');
    console.log('🔄 Running QR migrations...');
    for (let i = 0; i < migrations.length; i++) {
      await client.query(migrations[i]);
      process.stdout.write(`  ✓ ${i + 1}/${migrations.length}\r`);
    }
    await client.query('COMMIT');
    console.log('\n✅ QR migrations complete');
  } catch (err) {
    await client.query('ROLLBACK');
    console.error('❌ Migration failed:', err.message);
    throw err;
  } finally {
    client.release();
    pool.end();
  }
}

run().catch(console.error);
